{% set name = "python-stdnum" %}
{% set version = "1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff0e4d2b8731711cf2a73d22964139208088b4bd1a3e3b0c4f78d6e823dd8923

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python


test:
  imports:
    - stdnum

about:
  home: https://pypi.org/project/python-stdnum/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A Python module to parse, validate and reformat standard numbers and codes in different formats.

  description: |
    A Python module to parse, validate and reformat standard numbers and codes in different formats. It contains a large collection of number formats.
    Basically any number or code that has some validation mechanism available or some common formatting is eligible for inclusion in this library.

  doc_url: https://arthurdejong.org/python-stdnum/
  dev_url: https://arthurdejong.org/python-stdnum/

extra:
  recipe-maintainers:
    - kcemenike
